### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by viktorot** [viktorot/udacity-capstone-project#1]
delete

- [x] delete single

- [ ] delete multiple

tagging

- [x] display tag

- [x] remove tag

filtering

- [x]  by color

- [x] by tag

pinning

- [x] pin/unpin notification

- [x] open note from notificaion

design

- [x] list item update to show icon

- [x] list item update to show tag

- [x] update color scheme

- [x] update login menu to show anonymous user

- [x] update logout menu to show username/email when logged in

- [x] highlight selected color/filter/icon

- [x] filled icons for pin/tag when selected

fixes

- [x] landscape / tablet

- [x] save instance state

- [x] widget

- [x] hide delete on new note

- [x] highlight filter icon if enabled

- [x] set firebase permission

- [x] offline mode

- [x] scroll clickable

- [x] rich text editor

- [ ] tests

### improvements

alarm

firebase analytics / crash reporting

share intent

~~progress dialog when sending data to Firebase~~
